import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Locale } from "../../i18n-config";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: Locale };
}) {
  return (
    <html lang={locale} dir={locale === "en" ? "ltr" : "rtl"}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
